### ISSUE TITLE
Group Ruby Capstone

### ISSUE THREAD

**Issue by Danie12345** [marurevi/Ruby-capstone#30]
Link to kanban board [here](https://github.com/marurevi/Ruby-capstone/projects/1).

Members:
- @marurevi - Team member 1
- @Adanzeakonobi - Team member 2
- @Danie12345  - Team member 3

**Comment by addod19** [comment]
### Hi @Danie12345 , @marurevi and @Adanzeakonobi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Issue has a link, information about the number of people in the group, and list of usernames assigned to each team member :+1: 

## Required Changes ♻️
- [ ] It would be better if in the provided link in the issue, I should be redirected to the Kanban board as shown in the screenshot below

![Screenshot from 2022-08-01 16-02-15](https://user-images.githubusercontent.com/46388113/182192085-fbc311fc-2087-427c-9be0-9e972bc49d06.png)
However, here is where I was redirected to as shown below. Kindly check and fix it keeping in mind the project guidelines

![Screenshot from 2022-08-01 16-07-47](https://user-images.githubusercontent.com/46388113/182192426-16717e3d-1e40-4ec5-809e-8097c77b38e9.png)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dasileker** [comment]
### **Hi @marurevi,** 


**Nice job on making the required changes 🙌**

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
